### ISSUE TITLE
releasing without authentication

### ISSUE THREAD

**Issue by sdodson99** [sdodson99/headless-comments#12]
instead of tackling authentication, we could allow unauthenticated comments and require that client apps "verify" each comment.

for example:

1. a user would add a comment
2. our package would push that comment to Firestore with a `verified: false` flag
3. an admin of the client app could review the comment and flip to `verified: true` if it looks okay

a manual process like this sounds bizarre on the surface. however, it might not be that terrible for an initial release:

1. i feel like *most* apps get low enough traffic to handle a manual process like this
2. no one has to deal with authentication
3. no one has to deal with validation, spam, etc.
4. we'll end up shipping faster and getting community feedback earlier

of course, there's risk in this as well:

1. a manual process might put too much burden on clients and be undesirable
2. if we ever remove the `verified` flag behavior, there'd be possible debt in supporting backwards compatibility

or it might just be easier to build authentication from the start and avoid this nonsense???

**Comment by edodso2** [comment]
I would say lets just add  the verified flag. I don't really think we have to worry to much about backwards compatibility yet. If Next.js can change half their framework years later we can remove a `verified` flag 😂

Then, we can test out the current iteration on our own apps and think about docs, website, etc.

**Comment by sdodson99** [comment]
true 😂 I'd actually get a lot of value from this even with having to manually verify
