### ISSUE TITLE
Type-Safety for Firebase Database Interactions

### ISSUE THREAD

**Issue by sdodson99** [sdodson99/headless-comments#15]
Reading the Firebase Realtime Database response with `doc.data()` returns a TypeScript `any`. Currently, we make assumptions about the structure of the database response and blindly map the `any` response to a typed object:

```js
// text and createdAt could be anything!
const { text, createdAt } = doc.data();

return {
      id: doc.id,
      createdAt: createdAt.toDate(),
      text
};
```

We should consider leveraging some kind of runtime behavior, such as Zod, to validate the structure of the database response. We could also hand-roll the runtime validation if bundle size from an external package like Zod is concerning.

On the other hand, is this overkill? Should we have confidence that the database will have correctly structured data? What should we do if the runtime validation fails?

**Comment by edodso2** [comment]
I like the idea of validating. The most ideal would be to filter out comments that failed validation and log an error to the console. 

Maybe we start with just throwing an error if validation fails?

**Comment by edodso2** [comment]
Interesting read: https://github.com/colinhacks/zod/issues/485

Was eager to mess around with Zod since I had never used it before. This is what I came up with:

```TypeScript
export const Comment = z.object({
  id: z.string(),
  createdAt: z.preprocess(
    (timestamp): Date => (timestamp as Timestamp).toDate(),
    z.date()
  ),
  text: z.string(),
  verified: z.boolean(),
});

export type Comment = z.infer<typeof Comment>;
```

Went with `preprocess` because a 'post process' `transform` threw a bunch of errors.
