### ISSUE TITLE
Database & Structure

### ISSUE THREAD

**Issue by edodso2** [sdodson99/headless-comments#2]
### Database

Start with Firestore? Maybe we could support both in future.

### Structure

Considerations:
1. users might have a single firebase project for each page that needs comments
2. users might have multiple firebase project for each page that needs comments
3. users might store other items in their DB

With that being said, thoughts on below structure. 

<img width="820" alt="image" src="https://user-images.githubusercontent.com/12009947/215505368-77f149dd-96ac-433d-b0b9-5d489aa23ffb.png">

This structure adds new collection to the DB that will contain child collections of each page that needs comments. Our app could support passing an `id` or `name` field to headless-comments so it knows which child collection to read from. Also, since Firebase is so flexible, we could even have a generic `comments` collection as a child of the main collection for if the user wants a shared store. And this would be used if no `id` or `name` is passed to headless comments.

<img width="564" alt="image" src="https://user-images.githubusercontent.com/12009947/215506113-19963791-93a4-45a9-91e9-13727d830bd2.png">

**Comment by edodso2** [comment]
Awesome, I am currently trying to expose a list of comments to the example app via the `CommentsProvider` context.

**Comment by edodso2** [comment]
Do we have any outstanding items here or can we close @sdodson99?

**Comment by sdodson99** [comment]
Nope, good to close 👍
