### ISSUE TITLE
manage client side comment state

### ISSUE THREAD

**Issue by sdodson99** [sdodson99/headless-comments#9]
see #8 

we need to determine where and how to manage client side comment state.

1. inside `useComments` hook with comment state for single piece of content?
2. inside an app-level `<CommentsDataProvider />` with comment state for all pieces of content?
3. inside a content-level `<CommentsDataProvider />` ... or `<CommentSectionProvider />` ... with comment state for a single piece of content?

**Comment by edodso2** [comment]
Would number 2 be harder to incorporate into an MPA?

**Comment by sdodson99** [comment]
I think number 2 would be fine on an MPA. My fear is how it would behave on a SPA. If a user went to a bunch of popular blog posts, we'd load comments for each blog and the comments state could end up using a lot of memory.

**Comment by sdodson99** [comment]
Conceptually, I like number 3. The issue is that we're throwing so much setup on the client. For example, clients would have to:

1. Wrap their app in our existing `<FirebaseCommentsProvider />`
2. Wrap each blog post or blog post comment section in a `<CommentSectionProvider />`
3. Leverage hooks to interact with comments

Maybe that's not as bad as I imagine. In addition to the `<CommentSectionProvider />`, we could offer an alternative `withCommentSection()` HOC if clients don't want to use the wrapper provider.

**Comment by sdodson99** [comment]
> 1. Wrap their app in our existing `<FirebaseCommentsProvider />`
> 2. Wrap each blog post or blog post comment section in a `<CommentSectionProvider />`

We could also just merge all this into one provider that would wrap each blog post/piece of content. In other words, instead of the `<FirebaseCommentsProvider />` being defined at the app level, it would be defined around each blog post. That would allow it to safely manage comment state for each comment.

**Comment by sdodson99** [comment]
There's probably pros and cons to every option. We'll have to just pick whichever one is most logical and roll with it. Otherwise we'll never ship and figure out what users actually want lol.

I'm a fan of either of these two:

---
> Inside a content-level `<CommentsDataProvider />` ... or `<CommentSectionProvider />` ... with comment state for a single piece of content. In addition to the `<CommentSectionProvider />`, we could offer an alternative `withCommentSection()` HOC if clients don't want to use the wrapper provider.
---
> We could also just merge all this into one provider that would wrap each blog post/piece of content. In other words, instead of the `<FirebaseCommentsProvider />` being defined at the app level, it would be defined around each blog post.
---

**Comment by edodso2** [comment]
But in a MPA wouldn't you need to include `FirebaseCommentsProvider` on every page? So you would end up with something like:
```JavaScript
<FirebaseCommentsProvider firebaseApp={firebaseApp}>
  <CommentSectionProvider>
     <Comments />
   </CommentSectionProvider>
</FirebaseCommentsProvider>
```

**Comment by sdodson99** [comment]
True, you would have to include it on every page. But I feel like most apps have some kind of reusable App or Layout component for all their providers, so idk if there'd be much overhead. 

It would increase complexity to have all these providers though.

**Comment by edodso2** [comment]
I feel like its not a big deal to:

>We could also just merge all this into one provider that would wrap each blog post/piece of content. In other words, instead of the <FirebaseCommentsProvider /> being defined at the app level, it would be defined around each blog post.

only con is:
> but then we'd lose the benefit of centralized backend configuration that we have with the app-level provider.

But currently we have nothing in that provider. And the consuming application can easily expose the firebase app via a hook, context or whatever state management they are using.

**Comment by sdodson99** [comment]
I agree, I like that idea of combining them and not having the app level provider. Realistically, we probably won't need anything at app level anyways.

So final proposal is:

* Store comments state in `<FirestoreCommentsProvider />`
* Scope `<FirestoreCommentsProvider />` to each comment section
* Keep it named `<FirestoreCommentsProvider />`?

**Comment by edodso2** [comment]
Sounds good to me.
